# Generated by Django 3.2.16 on 2022-12-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0003_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='orange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='picture')),
            ],
        ),
    ]
