# Generated by Django 3.2.16 on 2022-12-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0004_orange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orange',
            old_name='price',
            new_name='buy_now',
        ),
    ]
