# Generated by Django 3.2.16 on 2022-12-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0005_rename_price_orange_buy_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orange',
            name='buy_now',
        ),
    ]
