# Generated by Django 3.2.16 on 2022-12-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0008_customer_say'),
    ]

    operations = [
        migrations.AddField(
            model_name='orange',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
